[project]
name = "trame-mui"
version = "0.1.0"
description = "MUI (React) widgets for trame"
authors = [
    {name = "Kitware Inc."},
]
dependencies = [
    "trame-client>=3,<5",
    "trame-server>=3.15,<5",
]
requires-python = ">=3.10"
readme = "README.rst"
license = {text = "MIT"}
keywords = ["Python", "Interactive", "Web", "Application", "Framework", "React"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "ruff",
    "pytest",
]
test = [
    "pytest",
    "pytest-asyncio",
    "pytest-playwright",
    "pytest-xprocess",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
  "/src/**/*.py",
  "/src/trame_mui/module/**",
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/trame_mui",
    "src/trame",
]

[tool.semantic_release]
version_variables = [
    "src/trame_mui/__init__.py:__version__",
]
version_toml = [
    "pyproject.toml:project.version",
]
build_command = """
  python -m venv .venv
  source .venv/bin/activate
  pip install -U pip build
  python -m build .
"""

[tool.ruff]
line-length = 88
